version: '3.9'

services:
  apache:
    build: ./apache
    ports:
      - "6007:80"
    volumes:
      - ./WebClient:/usr/local/apache2/htdocs
    depends_on:
      - python
    environment:
      - APACHE_LOG_DIR=/var/log/apache2

  python:
    build: 
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=restaurant
      - DB_USER=root
      - DB_PASSWORD=secret

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=restaurant
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
    volumes:
      - ./APIRest/database:/docker-entrypoint-initdb.d


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "7007:80"
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=secret
    depends_on:
      - mariadb
